#!/usr/bin/env fish

# global settings -------------------------------------------------------------

yabai -m config mouse_modifier fn
yabai -m config mouse_action1  move
yabai -m config mouse_action2  resize

# general space settings ------------------------------------------------------

yabai -m config layout                       bsp
yabai -m config top_padding                  24
yabai -m config bottom_padding               24
yabai -m config left_padding                 24
yabai -m config right_padding                24
yabai -m config window_gap                   24
yabai -m config window_placement             second_child
yabai -m config split_ratio                  0.50

# automations -----------------------------------------------------------------

# float system preferences
yabai -m rule --add app="^System Preferences\$" manage=off grid=4:4:1:1:2:2

# grid=<rows>:<cols>:<start-x>:<start-y>:<width>:<height>
set FOCUS_GRID "1:6:1:0:4:1"

set COMMUNICATION_APPS "^(Slack|Messages|Music|Spark)\$" 

if test (hostname) = "emmet"
  echo "Setting up Emmet-specific yabai"

  # Emmet has a 27" display so it can be a little more spacious.
  set FOCUS_GRID "1:6:1:0:4:1"

  set FOCUS_SPACE_INDEX 3
end

yabai -m space $FOCUS_SPACE_INDEX --label space_focus

yabai -m rule --add label="single-task-focus" \
  manage=off app=$COMMUNICATION_APPS grid=$FOCUS_GRID

yabai -m rule --add label="move-window-to-focus-space" \
  app=$COMMUNICATION_APPS space=^space_focus
